version: "3.9"

services:
  frontend:
    image: uweeds/frontend:latest
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
  
  backend:
    image: uweeds/backend:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://abhi:abhiramsai@postgres:5432/rust_server
      - SERVER_NAME=backend1
      - SERVER_PORT=8080
    depends_on:
      - postgres
    networks:
      - my_network

  backend2:
    image: uweeds/backend2:latest
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://abhi:abhiramsai@postgres:5432/rust_server
      - SERVER_NAME=backend2
      - SERVER_PORT=8081
    depends_on:
      - postgres
    networks:
      - my_network

  nginx:
    image: uweeds/my_nginxx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend 
      - backend2
    networks:
      - my_network
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=abhi
      - POSTGRES_PASSWORD=abhiramsai
      - POSTGRES_DB=rust_server
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
