#name: CI/CD Pipeline

#on:
  #push:
   # branches:
    #  - dev
  #schedule:
   # - cron: '0 0 * * *'

#jobs:
  #build-and-push:
   # runs-on: ubuntu-latest

   # steps:
    #- name: Checkout code
     # uses: actions/checkout@v2

   # - name: Login to Docker Hub
  #  uses: docker/login-action@v1
    #  with:
     #   username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

   # - name: Build and push Docker images
    #  run: |
     #   docker build -t uweeds/frontend:latest ./Frontend
      #  docker push uweeds/frontend:latest

       # docker build -t uweeds/backend:latest ./Backend
       # docker push uweeds/backend:latest

       # docker build -t uweeds/backend2:latest ./Backend
       # docker push uweeds/backend2:latest

       # docker build -t uweeds/nginx:latest ./nginx
       # docker push uweeds/nginx:latest

   # - name: Merge to master
    #  if: github.event_name == 'schedule'
     # run: |
      #  git checkout master
       # git merge dev
        #git push origin master

